##
## Copyright (c) 2022 Andrew E Page
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
## EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
## MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
## IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
## DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
## OR OTHER DEALINGS IN THE SOFTWARE.
##
name: Ubuntu, Mac, Windows
on:
  push:
  workflow_call:
    secrets:
      GITHUBPYTEST_ACCT_TOKEN:
        required: true
jobs:
  ##
  ## py 3.9
  ##
  Ubuntu_py3-9:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: syphar/restore-virtualenv@v1
      - name: Build
        run: |
          pip install --upgrade pip
          pip install install ./
          python --version
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: python -m unittest -v
  MacOSX_py3-9:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: syphar/restore-virtualenv@v1
      - name: Build
        run: |
          pip install --upgrade pip
          pip install install ./
          python --version
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: |
          echo token:  ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
          python -m unittest -v
  Windows_py3-9:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: syphar/restore-virtualenv@v1
      - name: Build
        run: |
          pip install --upgrade pip
          pip install install ./
          python --version
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: python -m unittest -v
  ##
  ## py 3.10
  ##
  Ubuntu_py3-10:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: syphar/restore-virtualenv@v1
        with:
          custom_cache_key_element: py310-ubuntu
      - name: Build
        run: |
          which pip
          which python
          python --version
          pip install --upgrade pip
          pip install install ./
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: python -m unittest -v
  MacOSX_py3-10:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: syphar/restore-virtualenv@v1
      - name: Build
        run: |
          pip install --upgrade pip
          pip install install ./
          python --version
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: python -m unittest -v
  Windows_py3-10:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: syphar/restore-virtualenv@v1
        with:
          custom_cache_key_element: py310-windows
      - name: Build
        run: |          
          pip install --upgrade pip
          pip install install ./
          python --version
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: python -m unittest -v
  ##
  ## py 3.11
  ##
  Ubuntu_py3-11:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: syphar/restore-virtualenv@v1
        with:
          custom_cache_key_element: py311-ubuntu
      - name: Build
        run: |
          which pip
          which python
          python --version
          pip install --upgrade pip
          pip install install ./
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: python -m unittest -v
  MacOSX_py3-11:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: syphar/restore-virtualenv@v1
      - name: Build
        run: |
          pip install --upgrade pip
          pip install install ./
          python --version
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: python -m unittest -v
  Windows_py3-11:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: syphar/restore-virtualenv@v1
        with:
          custom_cache_key_element: py311-windows
      - name: Build
        run: |          
          pip install --upgrade pip
          pip install install ./
          python --version
      - name: Test
        working-directory: unittests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}
        run: python -m unittest -v

  AllJobs:
    runs-on: ubuntu-latest
    needs:
      - Ubuntu_py3-9
      - MacOSX_py3-9
      - Windows_py3-9
      - Ubuntu_py3-10
      - MacOSX_py3-10
      - Windows_py3-11
      - Ubuntu_py3-11
      - MacOSX_py3-11
      - Windows_py3-11
    steps:
      - name: Announce
        run: echo "Success"
        
      
