name: PyPi Deploy
on:
  workflow_dispatch:
    inputs:
      SHA:
        description: 'Release Commit SHA'
        required: false
        default: "HEAD"
    
      versionNumber:
        description: 'Release Version Number'
        required: false
        default: "0.0.0"

jobs:
  BuildAndTest:
    uses: ./.github/workflows/build_and_test.yml
    secrets:
      GITHUBPYTEST_ACCT_TOKEN: ${{ secrets.GITHUBPYTEST_ACCT_TOKEN }}

  Dist:
    needs: [ BuildAndTest ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: pip
        run: |
          pip install --upgrade build
          pip install --upgrade twine
      - name: build
        run: python3 -m build
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/githubpy-${{ github.event.inputs.versionNumber }}-py3-none-any.whl
            dist/githubpy-${{ github.event.inputs.versionNumber }}.tar.gz
          retention-days: 1
